#ifndef CONFIG_LEGACY_CONTROL_REFERENCE_H
#define CONFIG_LEGACY_CONTROL_REFERENCE_H

/*
 * REFERENCE VALUES EXTRACTED FROM LEGACY FIELD CODE.
 * NOT APPROVED FOR ACTIVE CONTROL.
 * DO NOT INCLUDE THIS FILE FROM MOTOR OR APPLICATION CODE.
 */

#define LEGACY_REFERENCE_MAX_PRESSURE_N                    1500.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_CONTACT_THRESHOLD_N                 10.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_COARSE_THRESHOLD_N                  50.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_MICRO_THRESHOLD_N                   10.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_FINE_HOLD_THRESHOLD_N                1.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_HOLD_EXIT_THRESHOLD_N                2.0f  /* ACTIVE_IN_LEGACY_CODE */

#define LEGACY_REFERENCE_FIRST_APPROACH_V                     5.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_REAPPROACH_V                         2.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_UNUSED_CONTACT_PRESS_VMAX             2.5f  /* DEFINED_BUT_UNUSED */
#define LEGACY_REFERENCE_UNUSED_CONTACT_RELEASE_VMAX          -1.5f  /* DEFINED_BUT_UNUSED */
#define LEGACY_REFERENCE_MICRO_PULSE_MIN_V                    0.8f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_MICRO_PULSE_MAX_V                    3.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_FINE_PULSE_MIN_V                     0.4f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_FINE_PULSE_MAX_V                     1.0f  /* ACTIVE_IN_LEGACY_CODE */

#define LEGACY_REFERENCE_BASE_PULSE_MS                         10U  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_UNUSED_DEFAULT_PULSE_V                1.5f  /* DEFINED_BUT_UNUSED */
#define LEGACY_REFERENCE_CLAIMED_MIN_PULSE_MS                   2U  /* KNOWN_TIMING_INVALID */
#define LEGACY_REFERENCE_MECHANICAL_COOLDOWN_MS                30U  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_UNUSED_COOLDOWN_FIELD_MS             150U  /* DEFINED_BUT_UNUSED; CONFLICTING_DEFINITIONS */
#define LEGACY_REFERENCE_FRESH_FEEDBACK_TIMEOUT_MS            400U  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_PRESSURE_FEEDBACK_TIMEOUT_MS         500U  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_PRESSURE_JUMP_FILTER_N              80.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_GLITCH_FRAMES_REJECTED                 3U  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_GLITCH_ACCEPTED_ON_FRAME               4U  /* ACTIVE_IN_LEGACY_CODE */

#define LEGACY_REFERENCE_PULSE_BOOST_STEP_V                    0.3f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_MICRO_BOOST_MAX_V                     2.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_FINE_BOOST_MAX_V                      1.0f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_COARSE_BOOST_STEP_V                   0.5f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_COARSE_BOOST_MAX_V                    3.5f  /* ACTIVE_IN_LEGACY_CODE */
#define LEGACY_REFERENCE_REVERSE_BOOST_MULTIPLIER              0.5f  /* ACTIVE_IN_LEGACY_CODE */

#define LEGACY_REFERENCE_MANUAL_JOG_V                          1.0f  /* ACTIVE_IN_LEGACY_CODE; NEEDS_HARDWARE_VALIDATION */
#define LEGACY_REFERENCE_FAST_ONE_TOUCH_V                     10.0f  /* ACTIVE_IN_LEGACY_CODE; NEEDS_HARDWARE_VALIDATION */
#define LEGACY_REFERENCE_ACTIVE_OUTPUT_LIMIT_V                 6.0f  /* ACTIVE_IN_LEGACY_CODE; NEEDS_HARDWARE_VALIDATION */
#define LEGACY_REFERENCE_COMPLETION_ITERATIONS                  200U  /* ACTIVE_IN_LEGACY_CODE */

#define LEGACY_REFERENCE_CONTROL_INTERVAL_FIELD_MS               5U  /* ACTIVE_IN_LEGACY_CODE; CONFLICTING_DEFINITIONS */
#define LEGACY_REFERENCE_CONTROL_TASK_PERIOD_MS                  10U  /* ACTIVE_IN_LEGACY_CODE; CONFLICTING_DEFINITIONS */
#define LEGACY_REFERENCE_CLAIMED_CONTROL_PERIOD_MS               20U  /* COMMENT_ONLY; CONFLICTING_DEFINITIONS */

#endif
