#ifndef BOARD_RS485_RS485_BOARD_MAP_H
#define BOARD_RS485_RS485_BOARD_MAP_H

#include "stm32f4xx_hal.h"

#define RS485_BOARD_LEGACY_BAUD_RATE       115200U

#define RS485_BOARD_PORT1_UART             USART2
#define RS485_BOARD_PORT1_DE_RE_PORT       GPIOA
#define RS485_BOARD_PORT1_DE_RE_PIN        GPIO_PIN_1
#define RS485_BOARD_PORT1_TX_PORT          GPIOA
#define RS485_BOARD_PORT1_TX_PIN           GPIO_PIN_2
#define RS485_BOARD_PORT1_RX_PORT          GPIOA
#define RS485_BOARD_PORT1_RX_PIN           GPIO_PIN_3

#define RS485_BOARD_PORT2_UART             USART6
#define RS485_BOARD_PORT2_DE_RE_PORT       GPIOC
#define RS485_BOARD_PORT2_DE_RE_PIN        GPIO_PIN_8
#define RS485_BOARD_PORT2_TX_PORT          GPIOC
#define RS485_BOARD_PORT2_TX_PIN           GPIO_PIN_6
#define RS485_BOARD_PORT2_RX_PORT          GPIOC
#define RS485_BOARD_PORT2_RX_PIN           GPIO_PIN_7

#endif
