#ifndef PROTOCOL_MODBUS_PROTOCOL_CONSTANTS_H
#define PROTOCOL_MODBUS_PROTOCOL_CONSTANTS_H

#define MODBUS_FUNCTION_READ_COILS                 0x01U
#define MODBUS_FUNCTION_READ_HOLDING_REGISTERS     0x03U
#define MODBUS_FUNCTION_READ_INPUT_REGISTERS       0x04U
#define MODBUS_FUNCTION_WRITE_SINGLE_COIL          0x05U
#define MODBUS_FUNCTION_WRITE_SINGLE_REGISTER      0x06U

#define MODBUS_EXCEPTION_ILLEGAL_FUNCTION          0x01U
#define MODBUS_EXCEPTION_ILLEGAL_DATA_ADDRESS      0x02U
#define MODBUS_EXCEPTION_ILLEGAL_DATA_VALUE        0x03U
#define MODBUS_EXCEPTION_SERVER_DEVICE_FAILURE     0x04U

#define MODBUS_SINGLE_COIL_ON                      0xFF00U
#define MODBUS_SINGLE_COIL_OFF                     0x0000U
#define MODBUS_LEGACY_DEFAULT_STATION_ID            1U
#define MODBUS_LEGACY_SENSOR_DISCONNECTED_VALUE     0xFFFFU
#define MODBUS_RTU_REQUEST_LENGTH                    8U
#define MODBUS_RTU_MAX_READ_REGISTERS               11U

#endif
