#ifndef PROTOCOL_MODBUS_REGISTER_MAP_H
#define PROTOCOL_MODBUS_REGISTER_MAP_H

#define MODBUS_COIL_OPERATING_MODE                 0x0000U
#define MODBUS_COIL_AUTO_PRESSURE                   0x0001U
#define MODBUS_COIL_ONE_TOUCH_UP                    0x0002U
#define MODBUS_COIL_ONE_TOUCH_DOWN                  0x0003U
#define MODBUS_COIL_DIRECT_RELEASE_PULSE             MODBUS_COIL_ONE_TOUCH_UP
#define MODBUS_COIL_DIRECT_PRESS_PULSE               MODBUS_COIL_ONE_TOUCH_DOWN
#define MODBUS_COIL_JOG_OR_FAST_UP                  0x0004U
#define MODBUS_COIL_JOG_OR_FAST_DOWN                0x0005U

#define MODBUS_HOLDING_TARGET_PRESSURE              0x0000U
#define MODBUS_HOLDING_SECOND_TARGET_PRESSURE       0x0001U
#define MODBUS_HOLDING_STATION_ID_INACTIVE          0x0002U
#define MODBUS_HOLDING_BAUD_RATE_INACTIVE           0x0003U

#define MODBUS_INPUT_CONTROL_PRESSURE_UNITS         0x0000U
#define MODBUS_INPUT_RAW_PRESSURE_COUNTS            0x0001U
#define MODBUS_INPUT_MACHINE_STATE                  0x0002U
#define MODBUS_INPUT_MACHINE_FAULT                  0x0003U
#define MODBUS_INPUT_FAULT_DETAIL                   0x0004U
#define MODBUS_INPUT_LAST_COMMAND_RESULT            0x0005U
#define MODBUS_INPUT_LAST_MOTOR_ACTION              0x0006U
#define MODBUS_INPUT_LAST_MOTOR_COMMAND_MV          0x0007U
#define MODBUS_INPUT_PLANNED_TIM2_CCR3              0x0008U
#define MODBUS_INPUT_PLANNED_TIM3_CCR3              0x0009U
#define MODBUS_INPUT_STATUS_FLAGS                   0x000AU
#define MODBUS_INPUT_REGISTER_COUNT                 0x000BU
#define MODBUS_INPUT_DIAGNOSTIC_FRAME_BYTE_0         0x000BU
#define MODBUS_INPUT_DIAGNOSTIC_FRAME_BYTE_6         0x0011U
#define MODBUS_INPUT_LAST_MOTOR_FAILURE_RESULT       0x0012U
#define MODBUS_INPUT_LAST_MOTOR_FAILURE_STAGE        0x0013U
/* Append-only diagnostics. Multiword values are high word first. */
#define MODBUS_INPUT_SAMPLE_SEQUENCE_WORD_0          0x0014U
#define MODBUS_INPUT_SAMPLE_SEQUENCE_WORD_3          0x0017U
#define MODBUS_INPUT_SAMPLE_RECEIVED_MS_HIGH         0x0018U
#define MODBUS_INPUT_SAMPLE_RECEIVED_MS_LOW          0x0019U
#define MODBUS_INPUT_REQUEST_DIRECTION               0x001AU
#define MODBUS_INPUT_REQUEST_COMMAND_MV              0x001BU
#define MODBUS_INPUT_REQUEST_DURATION_MS             0x001CU
#define MODBUS_INPUT_REQUEST_SEQUENCE_HIGH           0x001DU
#define MODBUS_INPUT_REQUEST_SEQUENCE_LOW            0x001EU
#define MODBUS_INPUT_REQUEST_AT_MS_HIGH              0x001FU
#define MODBUS_INPUT_REQUEST_AT_MS_LOW               0x0020U
#define MODBUS_INPUT_TARGET_READBACK                 0x0021U
#define MODBUS_INPUT_AUTO_TARGET_CAPABILITY          0x0022U
#define MODBUS_INPUT_DEVICE_NOW_MS_HIGH              0x0023U
#define MODBUS_INPUT_DEVICE_NOW_MS_LOW               0x0024U
#define MODBUS_INPUT_TOTAL_REGISTER_COUNT            0x0025U
#define MODBUS_AUTO_TARGET_CAPABILITY_V1             0xA701U

#define MODBUS_STATUS_PRESSURE_FRESH_VALID          (1U << 0U)
#define MODBUS_STATUS_TARGET_VALID                  (1U << 1U)
#define MODBUS_STATUS_MOTOR_LOGICAL_ACTIVE          (1U << 2U)
#define MODBUS_STATUS_PHYSICAL_OUTPUT_LOCKED        (1U << 3U)
#define MODBUS_STATUS_PHYSICAL_OUTPUT_DISABLED      (1U << 4U)
#define MODBUS_STATUS_BENCH_RAW_COUNTS_CONTROL      (1U << 5U)
#define MODBUS_STATUS_BENCH_RELEASE_CORRECTION      (1U << 6U)

#endif
